package alexanders.mods.aoa.init;

import de.ellpeck.rockbottom.api.util.reg.ResourceName;

import static alexanders.mods.aoa.AllOfAlex.createRes;

public class Resources { // TODO: Implement this for other parts aswell? Remove this?
    public static ResourceName resourceDryFarmland;
    public static ResourceName resourceGrass;
    public static ResourceName resourceLongGrass;
    public static ResourceName resourceBlueBerryBush;
    public static ResourceName resourceRedBerryBush;
    public static ResourceName resourceUglyPlant;
    public static ResourceName resourceLargeUglyPlant;
    public static ResourceName shears;
    public static ResourceName drill;
    public static ResourceName drill_basic;
    public static ResourceName drill_copper;
    public static ResourceName drill_bit_basic;
    public static ResourceName drill_bit_copper;
    public static ResourceName pearlResource;
    public static ResourceName bouncyPearlResource;
    public static ResourceName rideablePearlResource;
    public static ResourceName miningPearlResource;
    public static ResourceName spikyPearlResource;
    public static ResourceName spawnPearlResource;
    public static ResourceName waypointPearlResource;
    public static ResourceName bridgingPearlResource;
    public static ResourceName cooldownResource;
    public static ResourceName pearlDescResource;
    public static ResourceName bouncyPearlDescResource;
    public static ResourceName rideablePearlDescResource;
    public static ResourceName miningPearlDescResource;
    public static ResourceName spikyPearlDescResource;
    public static ResourceName spawnPearlDescResource;
    public static ResourceName waypointPearlDescResource;
    public static ResourceName waypointPearlUsageDescResource;
    public static ResourceName bridgingPearlDescResource;
    public static ResourceName setToDescResource;
    public static ResourceName moreInfoDescResource;
    public static ResourceName phantomTileResource;
    public static ResourceName pearlOreResource;
    public static ResourceName slimeResource;
    public static ResourceName teleportationParticleResource;
    public static ResourceName bloodParticleResource;
    public static ResourceName bombResource;
    public static ResourceName miningBombResource;
    public static ResourceName bombLauncherResource;
    public static ResourceName resourceBricksBlue;
    public static ResourceName resourceBricksGreen;
    public static ResourceName resourceBricksGrey;
    public static ResourceName resourceBricksOrangeBrown;
    public static ResourceName resourceBricksPurple;
    public static ResourceName resourceBricksRed;
    public static ResourceName resourceBricksYellow;
    public static ResourceName resourceBricksYellowBrown;
    public static ResourceName resourceColourisedWoodAqua;
    public static ResourceName resourceColourisedWoodGoldBrown;
    public static ResourceName resourceColourisedWoodGreen;
    public static ResourceName resourceColourisedWoodGreenBrown;
    public static ResourceName resourceColourisedWoodPinkPurple;
    public static ResourceName resourceCrystalBlue;
    public static ResourceName resourceCrystalGreen;
    public static ResourceName resourceCrystalPurple;
    public static ResourceName resourceCrystalRed;
    public static ResourceName resourceCrystalYellow;
    public static ResourceName resourceSmoothStoneBlue;
    public static ResourceName resourceSmoothStoneGreen;
    public static ResourceName resourceSmoothStoneGrey;
    public static ResourceName resourceSmoothStoneOrange;
    public static ResourceName resourceSmoothStonePurple;
    public static ResourceName resourceSmoothStoneYellow;
    public static ResourceName resourcePillarHorizontalBeige;
    public static ResourceName resourcePillarVerticalBeige;
    public static ResourceName resourcePillarHorizontalBlue;
    public static ResourceName resourcePillarVerticalBlue;
    public static ResourceName resourcePillarHorizontalGreen;
    public static ResourceName resourcePillarVerticalGreen;
    public static ResourceName resourcePillarHorizontalGrey;
    public static ResourceName resourcePillarVerticalGrey;
    public static ResourceName resourcePillarHorizontalPurple;
    public static ResourceName resourcePillarVerticalPurple;
    public static ResourceName resourcePillarHorizontalPurpleBlue;
    public static ResourceName resourcePillarVerticalPurpleBlue;
    public static ResourceName resourcePlain;
    public static ResourceName resourceBrightLog;
    public static ResourceName resourceBrightLeaves;
    public static ResourceName resourceBrightSapling;
    public static ResourceName resourceAssimilatedTile;
    public static ResourceName resourceAssimilator;
    public static ResourceName resourceItemConduit;
    public static ResourceName resourceConduitLayer;
    public static ResourceName resourceRotateKey;
    public static ResourceName resourceSetWaypointKey;
    public static ResourceName resourceConduitLayerKey;
    public static ResourceName resourceOpenBombLauncherInventoryKey;
    public static ResourceName resourceGlass;
    public static ResourceName resourceSunBlue;
    public static ResourceName resourceSunGreen;
    public static ResourceName resourceSunOrange;
    public static ResourceName resourceSunPurple;
    public static ResourceName resourceSunRed;
    public static ResourceName resourceSunWhiteBlue;
    public static ResourceName resourceSunYellowBlue;
    public static ResourceName resourcePaintBomb;
    public static ResourceName resourceItemCannonContainer;
    public static ResourceName resourceBombCannonContainer;
    public static ResourceName resourceCannonGui;
    public static ResourceName resourceBombCannon;
    public static ResourceName resourceItemCannon;
    public static ResourceName resourceFunnel;
    public static ResourceName resourceMagnet;
    public static ResourceName resourceMagnetPulse;
    public static ResourceName resourceNoteTile;
    public static ResourceName resourceChangeNoteKey;
    public static ResourceName resourceChangeInstrumentKey;
    public static ResourceName resourceFilter;
    public static ResourceName resourceFilterGui;
    public static ResourceName resourceFilterContainer;
    public static ResourceName resourceRemoveFilterKey;
    public static ResourceName resourceIsBlacklist;
    public static ResourceName resourceIgnoreData;
    public static ResourceName resourceIgnoreMeta;
    public static ResourceName resourceJukebox;
    public static ResourceName resourceCycleJukeboxKey;
    public static ResourceName resourceJukeboxGui;
    public static ResourceName resourceConfigGui;
    public static ResourceName EFFECT_SPEED_ACTIVE;
    public static ResourceName EFFECT_JUMP_ACTIVE;

    public static void init() {
        resourceDryFarmland = createRes("dry_farmland");
        resourceGrass = createRes("grass");
        resourceLongGrass = createRes("long_grass");
        resourceBlueBerryBush = createRes("blue_berry_bush");
        resourceRedBerryBush = createRes("red_berry_bush");
        resourceUglyPlant = createRes("ugly_plant");
        resourceLargeUglyPlant = createRes("large_ugly_plant");
        shears = createRes("shears");
        drill = createRes("drill"); // Only used for entity registration
        drill_basic = createRes("drill_basic");
        drill_copper = createRes("drill_copper");
        drill_bit_basic = createRes("drill_bit_basic");
        drill_bit_copper = createRes("drill_bit_copper");
        pearlResource = createRes("pearl");
        bouncyPearlResource = createRes("bouncy_pearl");
        rideablePearlResource = createRes("rideable_pearl");
        miningPearlResource = createRes("mining_pearl");
        spikyPearlResource = createRes("spiky_pearl");
        spawnPearlResource = createRes("spawn_pearl");
        waypointPearlResource = createRes("waypoint_pearl");
        bridgingPearlResource = createRes("bridging_pearl");
        cooldownResource = createRes("cooldown");
        pearlDescResource = createRes("desc.pearl");
        bouncyPearlDescResource = createRes("desc.bouncy_pearl");
        rideablePearlDescResource = createRes("desc.rideable_pearl");
        miningPearlDescResource = createRes("desc.mining_pearl");
        spikyPearlDescResource = createRes("desc.spiky_pearl");
        spawnPearlDescResource = createRes("desc.spawn_pearl");
        waypointPearlDescResource = createRes("desc.waypoint_pearl");
        waypointPearlUsageDescResource = createRes("desc.waypoint_pearl_usage");
        bridgingPearlDescResource = createRes("desc.bridging_pearl");
        setToDescResource = createRes("desc.set_to");
        moreInfoDescResource = createRes("desc.more_info");
        phantomTileResource = createRes("phantom");
        pearlOreResource = createRes("pearl_ore");
        slimeResource = createRes("slime");
        teleportationParticleResource = createRes("particles.teleportation");
        bloodParticleResource = createRes("particles.blood");
        bombResource = createRes("bomb");
        miningBombResource = createRes("mining_bomb");
        bombLauncherResource = createRes("bomb_launcher");
        resourceBricksBlue = createRes("bricks.blue");
        resourceBricksGreen = createRes("bricks.green");
        resourceBricksGrey = createRes("bricks.grey");
        resourceBricksOrangeBrown = createRes("bricks.orange_brown");
        resourceBricksPurple = createRes("bricks.purple");
        resourceBricksRed = createRes("bricks.red");
        resourceBricksYellow = createRes("bricks.yellow");
        resourceBricksYellowBrown = createRes("bricks.yellow_brown");
        resourceColourisedWoodAqua = createRes("colourised_wood.aqua");
        resourceColourisedWoodGoldBrown = createRes("colourised_wood.gold_brown");
        resourceColourisedWoodGreen = createRes("colourised_wood.green");
        resourceColourisedWoodGreenBrown = createRes("colourised_wood.green_brown");
        resourceColourisedWoodPinkPurple = createRes("colourised_wood.pink_purple");
        resourceCrystalBlue = createRes("crystal.blue");
        resourceCrystalGreen = createRes("crystal.green");
        resourceCrystalPurple = createRes("crystal.purple");
        resourceCrystalRed = createRes("crystal.red");
        resourceCrystalYellow = createRes("crystal.yellow");
        resourceSmoothStoneBlue = createRes("smooth_stone.blue");
        resourceSmoothStoneGreen = createRes("smooth_stone.green");
        resourceSmoothStoneGrey = createRes("smooth_stone.grey");
        resourceSmoothStoneOrange = createRes("smooth_stone.orange");
        resourceSmoothStonePurple = createRes("smooth_stone.purple");
        resourceSmoothStoneYellow = createRes("smooth_stone.yellow");
        resourcePillarHorizontalBeige = createRes("pillar.horizontal.beige");
        resourcePillarVerticalBeige = createRes("pillar.vertical.beige");
        resourcePillarHorizontalBlue = createRes("pillar.horizontal.blue");
        resourcePillarVerticalBlue = createRes("pillar.vertical.blue");
        resourcePillarHorizontalGreen = createRes("pillar.horizontal.green");
        resourcePillarVerticalGreen = createRes("pillar.vertical.green");
        resourcePillarHorizontalGrey = createRes("pillar.horizontal.grey");
        resourcePillarVerticalGrey = createRes("pillar.vertical.grey");
        resourcePillarHorizontalPurple = createRes("pillar.horizontal.purple");
        resourcePillarVerticalPurple = createRes("pillar.vertical.purple");
        resourcePillarHorizontalPurpleBlue = createRes("pillar.horizontal.purple_blue");
        resourcePillarVerticalPurpleBlue = createRes("pillar.vertical.purple_blue");
        resourcePlain = createRes("plain");
        resourceAssimilatedTile = createRes("assimilated_tile");
        resourceAssimilator = createRes("assimilator");
        resourceBrightLog = createRes("bright_log");
        resourceBrightLeaves = createRes("bright_leaves");
        resourceBrightSapling = createRes("bright_sapling");
        resourceItemConduit = createRes("item_conduit");
        resourceConduitLayer = createRes("conduit");
        resourceRotateKey = createRes("rotate");
        resourceSetWaypointKey = createRes("set_waypoint");
        resourceConduitLayerKey = createRes("conduit_layer");
        resourceOpenBombLauncherInventoryKey = createRes("open_bomb_launcher_inventory");
        resourceGlass = createRes("glass");
        resourceSunBlue = createRes("sun.blue");
        resourceSunGreen = createRes("sun.green");
        resourceSunOrange = createRes("sun.orange");
        resourceSunPurple = createRes("sun.purple");
        resourceSunRed = createRes("sun.red");
        resourceSunWhiteBlue = createRes("sun.white_blue");
        resourceSunYellowBlue = createRes("sun.yellow_blue");
        resourcePaintBomb = createRes("paint_bomb");
        resourceItemCannonContainer = createRes("item_cannon_container");
        resourceBombCannonContainer = createRes("bomb_cannon_container");
        resourceCannonGui = createRes("cannon_gui");
        resourceBombCannon = createRes("bomb_cannon");
        resourceItemCannon = createRes("item_cannon");
        resourceFunnel = createRes("funnel");
        resourceMagnet = createRes("magnet");
        resourceMagnetPulse = createRes("magnet_pulse");
        resourceNoteTile = createRes("note_tile");
        resourceChangeNoteKey = createRes("change_note");
        resourceChangeInstrumentKey = createRes("change_instrument");
        resourceFilter = createRes("filter");
        resourceFilterGui = createRes("filter_gui");
        resourceFilterContainer = createRes("filter_container");
        resourceRemoveFilterKey = createRes("remove_filter");
        resourceIsBlacklist = createRes("isBlacklist");
        resourceIgnoreData = createRes("ignoreData");
        resourceIgnoreMeta = createRes("ignoreMeta");
        resourceJukebox = createRes("jukebox");
        resourceCycleJukeboxKey = createRes("cycle_jukebox");
        resourceJukeboxGui = createRes("jukebox_gui");
        resourceConfigGui = createRes("config_gui");
        EFFECT_SPEED_ACTIVE = createRes("effectSpeedActive");
        EFFECT_JUMP_ACTIVE = createRes("effectJumpActive");
    }
}
